services:
  - type: web
    name: object-detection-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT api_lite:app --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /health
